name: Deploy Prod (Manual)

on:
  workflow_dispatch: 

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Prod
        run: flyctl deploy --remote-only  # Ton app prod par défaut
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}